trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'uberspace'
    runOptions: 'commands'
    commands: 'cd BuliTorBot && git pull && /home/felixs/bin/pm2 restart all'
    failOnStdErr: false
  displayName: 'ssh task in uberspace VM'
